package com.dettle.app.orchestrator

import com.dettle.app.data.github.FileType
import com.dettle.app.data.github.GitHubClient
import com.dettle.app.data.github.RepoFile
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Compresses a GitHub repo into a token-efficient semantic map.
 *
 * Instead of sending 100,000 tokens of raw code to the AI,
 * this produces a ~2,000 token architectural map showing:
 * - Directory structure
 * - Function and class signatures (extracted via regex)
 * - File sizes
 *
 * Cached by commit SHA — never re-fetches an unchanged repo.
 */
@Singleton
class RepoMapper @Inject constructor(
    private val githubClient: GitHubClient
) {
    private val cache = mutableMapOf<String, String>()  // key = "owner/repo@branch"

    suspend fun buildRepoMap(
        owner: String,
        repo: String,
        branch: String = "main",
        maxSignatureFiles: Int = 20  // Limit deep-parsing to avoid rate limits
    ): Result<String> {
        val cacheKey = "$owner/$repo@$branch"
        cache[cacheKey]?.let { return Result.success(it) }

        val treeResult = githubClient.getRepoTree(owner, repo, branch)
        val files = treeResult.getOrElse { return Result.failure(it) }

        val map = buildString {
            appendLine("# Repository: $owner/$repo (branch: $branch)")
            appendLine("# Generated by Dettle RepoMapper")
            appendLine()

            // Directory tree (compact form)
            appendLine("## Directory Structure")
            appendLine("```")
            files.filter { it.type == FileType.DIRECTORY || it.size < 500_000 }
                .take(200)
                .forEach { file ->
                    val indent = "  ".repeat(file.path.count { it == '/' })
                    val prefix = if (file.type == FileType.DIRECTORY) "/" else ""
                    val sizeStr = if (file.type == FileType.FILE) " (${file.size}B)" else ""
                    appendLine("$indent$prefix${file.name}$sizeStr")
                }
            appendLine("```")
            appendLine()

            // Signature extraction for top code files
            appendLine("## Key File Signatures")
            appendLine()

            val codeFiles = files
                .filter { it.type == FileType.FILE && it.isCode && it.size < 100_000 }
                .sortedByDescending { it.size }  // Largest files first (likely most important)
                .take(maxSignatureFiles)

            appendLine("*Top ${codeFiles.size} code files by size:*")
            appendLine()

            for (file in codeFiles) {
                appendLine("### `${file.path}`")
                val sigResult = githubClient.readFile(owner, repo, file.path, branch)
                val signatures = sigResult.getOrNull()?.let { extractSignatures(it, file.extension) }
                if (!signatures.isNullOrEmpty()) {
                    appendLine("```${file.extension}")
                    signatures.forEach { appendLine(it) }
                    appendLine("```")
                } else {
                    appendLine("*(${file.size} bytes, no parseable signatures)*")
                }
                appendLine()
            }

            appendLine()
            appendLine("## Stats")
            appendLine("- Total files: ${files.count { it.type == FileType.FILE }}")
            appendLine("- Code files: ${files.count { it.isCode }}")
            appendLine("- Total size: ${files.filter { it.type == FileType.FILE }.sumOf { it.size }} bytes")
        }

        cache[cacheKey] = map
        return Result.success(map)
    }

    /** Extract function/class signatures from code content using language-aware regex */
    private fun extractSignatures(content: String, extension: String): List<String> {
        val lines = content.lines()
        return when (extension) {
            "kt", "java" -> lines.filter { line ->
                val trimmed = line.trim()
                (trimmed.startsWith("fun ") ||
                        trimmed.startsWith("class ") ||
                        trimmed.startsWith("interface ") ||
                        trimmed.startsWith("object ") ||
                        trimmed.startsWith("data class ") ||
                        trimmed.startsWith("sealed class ") ||
                        trimmed.startsWith("enum class ") ||
                        trimmed.startsWith("suspend fun ") ||
                        trimmed.startsWith("override fun ") ||
                        trimmed.startsWith("private fun ") ||
                        trimmed.startsWith("public ") ||
                        trimmed.startsWith("@") && trimmed.contains("fun "))
                        && !trimmed.startsWith("//")
            }.map { it.trimEnd('{').trimEnd() }

            "py" -> lines.filter { line ->
                val trimmed = line.trim()
                (trimmed.startsWith("def ") || trimmed.startsWith("class ") ||
                        trimmed.startsWith("async def ")) && !trimmed.startsWith("#")
            }.map { it.trimEnd(':') }

            "js", "ts", "jsx", "tsx" -> lines.filter { line ->
                val trimmed = line.trim()
                trimmed.startsWith("function ") ||
                        trimmed.startsWith("export function ") ||
                        trimmed.startsWith("export default function ") ||
                        trimmed.startsWith("export class ") ||
                        trimmed.startsWith("class ") ||
                        trimmed.startsWith("const ") && trimmed.contains("=>") ||
                        trimmed.startsWith("export const ") && trimmed.contains("=>")
            }.map { it.take(120) }

            "go" -> lines.filter { line ->
                val trimmed = line.trim()
                trimmed.startsWith("func ") || trimmed.startsWith("type ")
            }.map { it.trimEnd('{').trim() }

            "rs" -> lines.filter { line ->
                val trimmed = line.trim()
                trimmed.startsWith("pub fn ") || trimmed.startsWith("fn ") ||
                        trimmed.startsWith("pub struct ") || trimmed.startsWith("struct ") ||
                        trimmed.startsWith("pub enum ") || trimmed.startsWith("enum ") ||
                        trimmed.startsWith("impl ")
            }.map { it.trimEnd('{').trim() }

            "swift" -> lines.filter { line ->
                val trimmed = line.trim()
                trimmed.startsWith("func ") || trimmed.startsWith("class ") ||
                        trimmed.startsWith("struct ") || trimmed.startsWith("protocol ") ||
                        trimmed.startsWith("var ") || trimmed.startsWith("let ")
            }.map { it.trimEnd('{').trim() }

            else -> lines.filter { it.trim().isNotEmpty() }
                .take(30)  // For unknown file types, just take first 30 lines
        }.take(50)  // Max 50 signatures per file
    }

    fun invalidateCache(owner: String, repo: String, branch: String = "main") {
        cache.remove("$owner/$repo@$branch")
    }

    fun clearCache() = cache.clear()
}
